config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index'

  get 'welcome/index'

  root 'welcome#index'

  resources :films

end

app/models/film.rb
class Film < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
  end

  def new
    @film = Film.new
  end

  def edit
    @film = Film.find(params[:id])
  end

  def create
    imdb_params            = OMDB.title(film_params[:title])
    imdb_params[:category] = imdb_params.delete :type
    @film = Film.new(imdb_params)

    @film.save ? redirect_to(@film) : render('new')
  end

  def update
    @film = Film.find(params[:id])

    @film.update(film_params) ? redirect_to(@film) : render('edit')
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    redirect_to films_path
  end

  private

  def film_params
    params.require(:film).permit(:title, :plot, :imdb_rating, :runtime)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @film = Film.offset(rand(Film.count)).first
  end
end

app/controllers/main_frame_controller.rb
class MainFrameController < ApplicationController
  def index
    @film = Film.offset(rand(Film.count)).first
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/films/_form.html.slim
= simple_form_for @film, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form do |f|

  = f.error_notification

  = f.input :title, as: :string

  = f.input :plot, label: 'Duration', as: :text

  = f.input :imdb_rating, as: :string

  = f.input :runtime, as: :string

  = f.button :submit, class: 'btn btn-primary'

app/views/films/edit.html.slim
h1 Editing Film

div
  = render 'form'

  = link_to :back, films_path, class: 'btn btn-danger'

app/views/films/index.html.slim
h1 Films

.table-responsive
  table class="table-hover"
    thead
      th Title
      th IMDB Rate
      th Runtime
      th colspan="2"

    tbody
      - @films.each do |film|
        tr
          td = film.title
          td = film.imdb_rating
          td = film.runtime
          td = link_to 'More info', film_path(film)
          td = link_to 'Edit', edit_film_path(film)
          td = link_to 'Remove', film_path(film),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }

= link_to 'New Film', new_film_path
= link_to 'Back', :home

app/views/films/new.html.slim
h1 Neu Film

.container
  = simple_form_for @film, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form do |f|

    = f.error_notification

    = f.input :title, as: :string

    = f.button :submit, class: 'btn btn-primary'

  = link_to :back, films_path, class: 'btn btn-danger'

app/views/films/show.html.slim
p
  strong = @film.title

p
  strong Year:
  = @film.year

p
  strong Description:
  = @film.plot

p
  strong Genre:
  = @film.genre

p
  strong Director:
  = @film.director

p
  strong Writer:
  = @film.writer

p
  strong Actors:
  = @film.actors

p
  strong Country:
  = @film.country

p
  strong Awards:
  = @film.awards

p
  strong Category:
  = @film.category

p
  strong IMDB Rate:
  = @film.imdb_rating

p
  strong Runtime:
  = @film.runtime


= link_to 'Back', films_path
= link_to 'Edit', edit_film_path(@film)

app/views/home/index.html.slim
= image_tag "logo.jpg"

.content
  = link_to "Give me another movie!", url_for(params), class: "g-m-m"

  p
    strong Title:
    = @film.title

  p
    strong Description:
    = @film.plot

  p
    strong IMDB Rate:
    = @film.imdb_rating

  p
    strong Runtime:
    = @film.runtime

  = link_to "See all", films_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Filmzeit
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

body
	.container
		= yield

app/views/welcome/index.html.slim
= image_tag "hallo.jpg"

.content
  = link_to "Give me a movie!", :home